// frontend/angular/src/app/components/login/login.component.ts
import { Component } from '@angular/core';
import {AuthenticationRequest} from "../../models/authentication-request";
import {AuthenticationService} from "../../services/authentication/authentication.service";
import {Router} from "@angular/router";

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
   authenticationRequest:AuthenticationRequest={username:'',password:''};

   errorMsg='';
   constructor(private authenticationService:AuthenticationService,
               private router:Router) {}

   login() {
       this.errorMsg='';
       this.authenticationService.login(this.authenticationRequest)
         .subscribe({
           next: (authenticationResponse)=>{
             // console.log(authenticationResponse);

             localStorage.setItem("user",JSON.stringify(authenticationResponse));
             this.router.navigate(["customers"]);
           },
           error: (err)=> {
             console.log(err);
             console.log(err.status);
             if (err.status ===401) {
               this.errorMsg="Login and / or password is incorrect."
             }
           }
         });
   }
}

<div class="flex" style="height: 100vh;">
  <div class="col-6 m-3 flex flex-column justify-content-center">
    <div class="m-auto">
      <div class="text-center">
        <p-avatar
          image="https://user-images.githubusercontent.com/40702606/210880158-e7d698c2-b19a-4057-b415-09f48a746753.png"
          styleClass="mr-2" size="xlarge" shape="circle"></p-avatar>
        <h1>Sign in to your account</h1>

      </div>

      <div>
        <p-message *ngIf="errorMsg" severity="error" [text]="errorMsg" styleClass="mb-2"></p-message>
      </div>

      <div class="field">
        <label for="email">Email</label>
        <input pInputText id="email" class="w-full" type="email" name="email" placeholder="Jane@amigoscode.com"
        [(ngModel)]="authenticationRequest.username"/>
      </div>
      <div class="field">
        <label for="password">Password</label>
        <input pInputText id="password" class="w-full" type="password" name="password"
               placeholder="Type your password"
        [(ngModel)]="authenticationRequest.password"/>
      </div>
      <button pButton label="Login" class="w-full" (click)="login()"></button>
      <button pButton label="Don't have an account? Signup now."
              class="p-button-link w-full text-left pl-0"
              [routerLink]="['/register']"></button>
    </div> </div>
  <div class="col-6 flex flex-column justify-content-end align-items-center right-container">
   <h1><a href="https://www.amigoscode.com/courses" target="_blank">Enroll Now</a></h1>
    <img
      class="background p-6 pt-0"
      src="https://user-images.githubusercontent.com/40702606/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png"/>
  </div>
</div>

// frontend/react/src/components/login/Login.jsx
import {
    Box,
    Button,
    Flex,
    FormLabel,
    Heading,
    Input,
    Link,
    Stack,
    Image,
    Text,
    Alert,
    AlertIcon
} from '@chakra-ui/react';

import {Formik, Form, useField, setNestedObjectValues} from "formik";
import * as Yup from "yup";
import { useEffect, useRef} from "react";
import {useAuth} from "../context/AuthContext"
import {errorNotification} from "../../services/notification"
import {useNavigate} from 'react-router-dom'
import RegisterCustomerDrawer from "../RegisterCustomerDrawer"

const MyTextInput = ({ label, ...props }) => {
    // useField() returns [formik.getFieldProps(), formik.getFieldMeta()]
    // which we can spread on <input>. We can use field meta to show an error
    // message if the field is invalid and it has been touched (i.e. visited)
    const [field, meta] = useField(props);
    return (
        <Box>
            <FormLabel htmlFor={props.id || props.name}>{label}</FormLabel>
            <Input className="text-input" {...field} {...props} />

            {meta.touched && meta.error ? (
                <Alert className="error" status={"error"} mt={2}>
                    <AlertIcon/>
                    {meta.error}
                </Alert>
            ) : null}


        </Box>
    );
};

const LoginForm = () => {
    const {login}=useAuth();
    const navigate=useNavigate();

    return (
    <Formik
              validateOnMount={true}
              validationSchema={Yup.object(
                {
                    username: Yup.string()
                        .email("Must be a valid email")
                        .required("Email is required"),
                    password: Yup.string()
                        .max(20,"Password cannot be more than 20 characters")
                        .required("Password is required")
                }
              )
            }
            initialValues={{username:'',password:''}}

            onSubmit={(values,{setSubmitting})=>{
                setSubmitting(true)
                // alert(JSON.stringify(values,null,0));
                login(values).then(res=> {
                    // navigate to dashboard
                    navigate("/dashboard/customers")
                   console.log("successfully logged in")
                }).catch(err=>{
                     // errorNotification(err.code,err.response.data.message);
                     console.log(err)
                }).finally(()=>{
                    setSubmitting(false)
                })
            }}>

        {
            ({isValid,isSubmitting, dirty})=>{
                // console.log("isValid="+isValid+", isSubmitting="+isSubmitting)
                return (
            <Form>
                <Stack spacing={15}>
                        <MyTextInput
                            label={"Email"}
                            name={"username"}
                            type={"text"}
                            placeholder={"hello@amigoscode.com"}
                        />
                    <MyTextInput
                        label={"Password"}
                        name={"password"}
                        type={"password"}
                        placeholder={"Type your password"}
                    />
                    <Button isDisabled={!isValid|| isSubmitting}  type="submit">
                         Login
                    </Button>

                </Stack>

            </Form>
           )}
        }

    </Formik>
   );
};

const Login= ()=> {
    const {customer, isCustomerAuthenticated}=useAuth()
    const navigate=useNavigate()

    useEffect(()=>{

        if (isCustomerAuthenticated()) {
            navigate("/dashboard/customers")
        }
    },[])



    return (
        <Stack minH={'100vh'} direction={{ base: 'column', md: 'row' }}>
            <Flex p={8} flex={1} alignItems={'center'} justifyContent={'center'}>
                <Stack spacing={4} w={'full'} maxW={'md'}>
                    <Stack alignItems={'center'} >
                    <Image
                        src={'https://user-images.githubusercontent.com/40702606/210880158-e7d698c2-b19a-4057-b415-09f48a746753.png'}
                    boxSize={"200px"}
                    alt={"Amigoscode Logo"}/>
                    </Stack>
                    <Heading fontSize={'2xl'} mb={15}>Sign in to your account</Heading>
                     <LoginForm/>

                    <Link color={"blue.500"} href={"/signup"}>Don't have an account? Sign up now.</Link>
                </Stack>
            </Flex>
            <Flex flex={1} p={10} flexDirection={'column'}
            alignItems={'center'} justifyContent={'center'}
            bgGradient={{sm:'linear(to-r,blue.600,purple.600)'}}>
                <Text fontSize={'6xl'} color={'white'} fontWeight={'bold'} mb={5}>
                    <Link href={"https://amigoscode.com/courses"}>Enrol Now</Link>
                </Text>
                <Image
                    alt={'Login Image'}
                    objectFit={'scale-down'}
                    src={
                        'https://user-images.githubusercontent.com/40702606/215539167-d7006790-b880-4929-83fb-c43fa74f429e.png'
                    }
                />
            </Flex>
        </Stack>
    );
}

export default Login
